project_id = "wpwyunfwsqmqftlpihxc"

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.auto-release-transactions]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.check-connect-status]
verify_jwt = false

[functions.create-connect-login-link]
verify_jwt = false

[functions.submit-external-listing]
verify_jwt = false

[functions.import-external-listings]
verify_jwt = false